source 'https://rubygems.org'
gemspec
gem 'tramway-user', path: '../tramway-user'
gem 'tramway-core', path: '../tramway-core'
gem 'haml-rails'
gem 'sass-rails'
gem 'bootstrap', '~> 4.0.0.beta2.1'
gem 'audited'
gem 'simple_form'
gem 'font-awesome-rails'
gem 'coffee-rails'
